### ISSUE TITLE
The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.

### ISSUE THREAD

**Issue by fishfree** [jupyter/nbgrader#1009]
### Operating system: 
Ubuntu 16.04 64bit
### `python --version`
3.6.3
### `nbgrader --version`
0.5.4
### `jupyterhub --version` (if used with JupyterHub)
0.9.2
### `jupyter notebook --version` 
5.6.0
### Expected behavior
NBgrader will work perfectly.
### Actual behavior
Cannot release and collect
### Steps to reproduce the behavior
run under root ( BTW: I also installed my JupyterHub using root)
# jupyterhub --no-ssl --config=/etc/juypterhub/jupyterhub_config.py --debug
Then open browser and log in, on the "Manage Assignments" page, it shows:
The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.

~~~~~~~
Please give me a valid nbgrader_config.py and tell me where to put it.

**Comment by isaurssaurav** [comment]
> ### Operating system:
> Ubuntu 16.04 64bit
> 
> ### `python --version`
> 3.6.3
> 
> ### `nbgrader --version`
> 0.5.4
> 
> ### `jupyterhub --version` (if used with JupyterHub)
> 0.9.2
> 
> ### `jupyter notebook --version`
> 5.6.0
> 
> ### Expected behavior
> NBgrader will work perfectly.
> 
> ### Actual behavior
> Cannot release and collect
> 
> ### Steps to reproduce the behavior
> run under root ( BTW: I also installed my JupyterHub using root)
> 
> # jupyterhub --no-ssl --config=/etc/juypterhub/jupyterhub_config.py --debug
> Then open browser and log in, on the "Manage Assignments" page, it shows:
> The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.
> 
> ```
> Please give me a valid nbgrader_config.py and tell me where to put it.
> ```



> ### Operating system:
> Ubuntu 16.04 64bit
> 
> ### `python --version`
> 3.6.3
> 
> ### `nbgrader --version`
> 0.5.4
> 
> ### `jupyterhub --version` (if used with JupyterHub)
> 0.9.2
> 
> ### `jupyter notebook --version`
> 5.6.0
> 
> ### Expected behavior
> NBgrader will work perfectly.
> 
> ### Actual behavior
> Cannot release and collect
> 
> ### Steps to reproduce the behavior
> run under root ( BTW: I also installed my JupyterHub using root)
> 
> # jupyterhub --no-ssl --config=/etc/juypterhub/jupyterhub_config.py --debug
> Then open browser and log in, on the "Manage Assignments" page, it shows:
> The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.
> 
> ```
> Please give me a valid nbgrader_config.py and tell me where to put it.
> ```

Did you put `nbgrader_config.py` file before or after jupyter-notebook spwaned ?
It just happens to be that `nbgrader_config.py` file should be in its destination (`/home/[user_name]`) **_before a notebook is spawned_**.
So either you can place` nbgrader_config.py` file at` pre_spwan hook` , or attached into singleuser's image file.

**Comment by tonyweed** [comment]
Hi, can you take more of a look into why this occurs? I'm running into the same issue here, and do have a valid nbgrader_config.py file in the directory where jupyterhub is running from.

**Comment by isaurssaurav** [comment]
> Hi, can you take more of a look into why this occurs? I'm running into the same issue here, and do have a valid nbgrader_config.py file in the directory where jupyterhub is running from.

I had a same error while back. It just happens to be that nbgrader_config.py file should be in its destination ( /home/{username}) before a user is spawned.
So either you can place nbgrader_config.py file at pre_spwan hook , or attached into singleuser's image file.

**Comment by scott2b** [comment]
This seems to have been closed without resolution. Could we get a resolution that includes a minimal config file, where to put it, and what the permissions should be set to? Or a pointer to the relevant part of the docs? As far as I can tell the docs do not answer these questions.

**Comment by sebhoa** [comment]
I use jupyter notebook standalone... I'm not sure to understand how to create 'course'... I run my jupyter server in a standard directory : `/Users/seb/my_courses/` But when I click Formgrader menu the `Manage Assignments` window appear but with the warning message: 

> The course id has not been set in nbgrader_config.py...

And I can create assignment, not course. So ?

**Comment by jhamrick** [comment]
The exact setup differs depending on your use case, but please see here for several example setups: https://nbgrader.readthedocs.io/en/master/configuration/jupyterhub_config.html

Please feel free to open a new issue with specific details about your particular use case and setup if you are still having problems.

**Comment by mauro-cosentino** [comment]
Hello there,

this is issue is happening to me know, and I couldn't find a solution in the docs. I have looked for in the "Setting up the exchange" session, but everything proposed there I implemented already and the issue does not go away.

Just to make sure what the issue is (maybe not identical to this thread): when I start the formgrader I always receive the message: 
_The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.
I can create and I can generate the assignment. However, when I place a sample of an answered assignment in the submitted directory_

I can create and generate an assignment. But even if I follow the steps of this tutorial: https://rb.gy/umbdfx
when I include my submitted folder with one answered notebook the "# Submissions" in the formgrader panel continues to be 0 (zero) and I can't perform the autograding.

I am using the nbgrader standalone (no JupyterHub) and my OS is Ubuntu 20.04. The relevant software for nbgrader versions are:
python: 3.8.5 (although it coexists in my system with version 2.7, this is the one the notebook kernels are running in)

$ nbgrader --version
Python version 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
nbgrader version 0.6.1

$ jupyter notebook --version
5.7.8

Thanks for any help,
M.

**Comment by dnit13** [comment]
@jhamrick link not found.
