### ISSUE TITLE
"generate" (formgrader) and "assign" (command line) refer to same thing

### ISSUE THREAD

**Issue by rkdarst** [jupyter/nbgrader#1136]
I was getting ready to submit a diagram outlining nbgrader steps and carefully defining all of the terms that are used, when I realized something: in formgrader, creating the student version of assignments is called "generate", while from the command line it is called "assign".  The formgrader term sounds more accurate, I guess because it came second.

I guess it would be nice to call the command line option `generate`, but also not practical to change.  Or, one could make an alias, but still most solutions I can think of will make things more confusing.

Just a comment, if nothing can be done this can be closed as a reference for the future.

**Comment by jhamrick** [comment]
I think that's a great point. In #1120 we're considering changing the name `nbgrader feedback` to `nbgrader generate_feedback`, and I think it's reasonable to maybe also change `nbgrader assign` to `nbgrader generate_assignment`, possibly keeping an alias around for a while so that `assign` doesn't immediately go away.
