### ISSUE TITLE
Possible to fetch feedback for only some notebooks in an assignment

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#1141]
If feedback has been generated and released for an assignment, and then one notebook changes and the assignment is resubmitted, then when the student clicks "fetch feedback" (before the new feedback is available) the feedback will be fetched for the unchanged notebook but not the changed notebook. This gives the reverse impression than what I think there should be: that there is new feedback available for the unchanged notebook (false) and there is no feedback available for the changed notebook (true at the moment, but might be false in the future). I think in this case it should detect that new feedback for the new submission is not yet available.

Steps to reproduce:
1. Submit an assignment.
2. Generate and release feedback for the assignment.
3. Fetch feedback for the assignment.
4. Make a change to one notebook in an assignment (but not all notebooks).
5. Resubmit assignment.
6. Fetch feedback for the assignment. Note that this succeeds, and that there is only feedback available for the notebook(s) that did not change.

**Comment by dsblank** [comment]
@jhamrick Are you doing the steps through the UI or the command line?

I see a related issue (or same issue):  I can't generate new feedback if I regrade one of two notebooks. I will explore further.

**Comment by jhamrick** [comment]
This was through the web interface. Thanks for investigating!

**Comment by dsblank** [comment]
These are notes to myself as I explore the issue (so I don't forget... may take a few days to resolve). Also, not sure these notes are the same, related, or different issue as above.

1. It appears that `converters/base.py:init_destination` isn't detecting newer graded assignments so that we can re-generate
2. It appears that even if forced to generate feedback, and then released, the student fetch operation is not detecting newer feedback (which should show "ready to fetch" message next to submission and the "Fetch Feedback" button.
