### ISSUE TITLE
exchange folder management and permissions question

### ISSUE THREAD

**Issue by Wildcarde** [jupyter/nbgrader#1174]
### Operating system
Will likely be a centos 7 base with a shared nfs storage backending jupyterhub for a class
### `nbgrader --version`
Will be latest when rolled out
### `jupyterhub --version` (if used with JupyterHub)
Will also be latest

### Expected behavior
Exchange folders that isolate students from each other and protect the assignment copies of the files.
### Actual behavior
Current documentation seems to imply there is a single exchange folder that nbgrader retrieves assignments from for individual students after they have been published out by the professor / TA. However the root folder is set to `ugo+rw` allowing students to write to the same space assignments come in from. It is however not clear what the permissions on `/tmp/exchange/example_course/outbound/ps1` are in the example. Similarly it's not clear what the resultant permissions are for `/tmp/exchange/example_course/inbound/`.  Ideally I'd like to be able to setup a situation where:
`/tmp/exchange/example_course/outbound/` is read only by students.  
and  
`/tmp/exchange/example_course/inbound/` is write only so they are unable to see neighboring files in the folder.

The unix permissions / group strategy expected for these folders is not discussed in the documentation either so i'm a bit fuzzy on exactly how separation of interests is being maintained.

**Comment by jhamrick** [comment]
> Ideally I'd like to be able to setup a situation where: /tmp/exchange/example_course/outbound/ is read only by students. and /tmp/exchange/example_course/inbound/ is write only so they are unable to see neighboring files in the folder.

Yes, this is how nbgrader configures things automatically. The toplevel folder has to be readable and writeable by everybody but the permissions of the subdirectories are set so that students won't be able to modify released assignments and so they can't read (or modify) each others' submissions.

Specifically:
* `/tmp/exchange/example_course` is 0775
* `/tmp/exchange/example_course/outbound/` is 0775
* `/tmp/exchange/example_course/inbound/` is 0733 with set GID so student submission will have the instructors group. This means students can write to inbound but can't read it.
* Individual submissions are 0777 so the instructor can delete them if necessary. However, the submission names are hidden from other users by the timestamp and a random string (and the inbound directory is not listable, so you need to know the exact filename).

This is not a perfect solution but it works well enough for now. At some point we will have a new exchange service which will handle permissions in a cleaner way.

**Comment by Wildcarde** [comment]
Thanks for the info! I'm currently in the middle of trying to figure out how to make sure students / instructors actually have groups inside their containers at all so that I can actually use this. 

Another question, how is isolation handled when the instructors grade notebooks? ie, how are students prevented from submitting malicious notebooks that either damage the state of the class assignments or lift credentials from the instructors?

**Comment by jhamrick** [comment]
>  how are students prevented from submitting malicious notebooks that either damage the state of the class assignments or lift credentials from the instructors?

By default, there's nothing preventing this, but there is a way you can get nbgrader to do grading inside of a docker container which offers more protection: https://nbgrader.readthedocs.io/en/master/user_guide/advanced.html#grading-in-docker

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
