### ISSUE TITLE
Use better colors for full credit and no credit

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#122]
Ideally this would be much subtler. It's the kind of thing the user will understand immediately. I'd recommend making the buttons the same color as the background, white text, and make a faint border so that you know they're buttons.

**Comment by jhamrick** [comment]
I don't think I'll have time anytime soon to change this, though I agree the design could be better. If you wanted to make a mock up in illustrator or something with the exact colors and design you're thinking of, that would help a lot -- or better yet, a PR :smile: Otherwise, I probably will get to this later in the semester.
