### ISSUE TITLE
nbgrader tests.

### ISSUE THREAD

**Issue by amihal01** [jupyter/nbgrader#1314]
Hello everyone,

is it possible to take output from Jupyter Notebook shell, and compare is it good written?
Task is, for example, **write "Hello World" in Python.**

I want to check, **with nbgrader**,  is it output equal to "Hello World"

Thank you

**Comment by perllaghu** [comment]
I think this is more a jupyter notebook question, rather than a grader question.

nbgrader basically works by either checking notebook cells work without error, or by comparing the students submitted work to the instructors source notebook

You can certainly test that a student has a notebook cell with the contents `print("helllo world")` in it.

What are you trying to achieve here?

**Comment by willingc** [comment]
I'm going to close this issue. @amihal01, Jupyter's discourse discussion channels are a good place for these questions too.
