### ISSUE TITLE
NBgrader using MySQL DB instead of sqlite

### ISSUE THREAD

**Issue by whositwhatnow** [jupyter/nbgrader#1344]
Hello,

Currently i'm using JupyterHUb and Mysql for the DB.  I know nbgrader uses default sqlite.  I am wondering if nbgrader can use mysql for the DB.

**Comment by perllaghu** [comment]
nbgrader _can_ use other databases..... I'm just not sure what the benefit it.

NBGrader uses a combination of

- files that exist in `source` & `release` folders (for formgrader)
- files that exist in _outbound_ & _assignment_id_ folders (for assignments)
- files that exist in _inbound_ & _submitted_ (for formgrader)

..... the database is used to keep copies of notebook marking schemes, and rewards - and is built to be personal to an instructor. Off-loading that file to an external database-server means you need a database for each instructor.

**Comment by whositwhatnow** [comment]
I've had some issues using sqlite for the gradebookdb.  You are creating a new db for each instructor anyways so its not an issue in my setup. 

just as a note I am using the mysqlconnector 


e.g. c.CourseDirectory.db_url = 'mysql+mysqlconnector://{}:{}@{}/{}{}'.format("mysqldbuser","mysqlpassword","localhost","mysqldb","")

**Comment by whositwhatnow** [comment]
thanks for comment, its working as expected for now using above coursedirectory db.

**Comment by jhamrick** [comment]
> nbgrader can use other databases..... I'm just not sure what the benefit it.

Just thought I'd  also mention this answer in the FAQ, for future reference: https://nbgrader.readthedocs.io/en/stable/user_guide/faq.html#do-i-have-to-use-sqlite-for-the-nbgrader-database

_Do I have to use sqlite for the nbgrader database?_

_No, and in fact, if you have multiple people grading accessing the formgrader at the same time we strongly encourage you not to use sqlite because it is not threadsafe. Postgres is also supported, and anything else that works with SQLAlchemy is likely to work (e.g. MySQL), though only sqlite and Postgres have been tested._
