### ISSUE TITLE
Access database for all the instructors

### ISSUE THREAD

**Issue by major-project-1921** [jupyter/nbgrader#1683]
1. How to access the databse in  each pod from outside?

**Comment by perllaghu** [comment]
They are not designed to be.

The databases [`gradebook.db`] are SQLite databases, so designed to be access by a local process.

If you _need_ to access the database, you'll need to ssh into the docker instance & use command-line tools.

If, on the other hand, you're looking to have multiple instructors accessing a _common_ database - I suggest you actually configure nbgrader to use an external database.... however note that the autograde process assumes that the source version is available on disk - so that'll cause a knock-on challenge.

**Comment by perllaghu** [comment]
(I suggest we close this now)

**Comment by brichet** [comment]
Closing as suggested
