### ISSUE TITLE
404 not found error when downloading assignments 

### ISSUE THREAD

**Issue by jrasero** [jupyter/nbgrader#1726]
Hi,

I've set up nbgrader with jupyterhub and I am able to release assignments, but any time that me (as the admin and instructor) or a student tries to download the assignment after fetching it, it gives 404 error (see picture attached).

I guess there's some issue with the paths, but so far I have not been able to figure out what's going on, so any help would be really really appreciated!

Thanks!!!

![Captura de pantalla de 2023-01-18 18-42-14](https://user-images.githubusercontent.com/25054369/213319278-67584dcb-74fc-41f7-b58b-fb17b7584b50.png)

### Operating system
Ubuntu 20.04.5 LTS
### `nbgrader --version`
nbgrader version 0.8.1
### `jupyterhub --version` (if used with JupyterHub)
1.5.0
### `jupyter notebook --version` 
6.4.12

**Comment by DevBrunoo** [comment]
great

**Comment by tuncbkose** [comment]
I don't know much about the JupyterHub side of things but it looks weird to me that you are trying to access `exchange/assignment/notebook.ipynb` because usually the format (at least what I see when I didn't do anything special beyond setting an exchange directory) is:
```
exchange
|-course
|--inbound
|---submission
|----notebooks
|--outbound
|---assignment
|----notebooks
```
Plus I am not sure what you mean by "downloading after fetching", because fetching is the act of downloading (or copying) from the exchange.

**Comment by brichet** [comment]
I'm closing it as answered.

Feel free to open it again if this is not the case.
