### ISSUE TITLE
nbgrader push and pull for assignment distribution and turning in

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#198]
I think I have figured out a simple way of creating two new nbgrader commands, push and pull, that will make it easy for instructors and students to manage assignments. Initially it commands will assume that nbgrader is deployed on a single JupyterHub instance, but I think it won't be difficult to make the design scale to other usage cases. The big issue that this will solve is allowing multiple instructors teaching multiple classes with different students in each class. It doesn't require instructors to have any special permissions on the system so the sys-admin and dev-ops load will be simple.

The idea is the build a set of directories in a centralized place like `/srv/nbgrader/exchange.` I am still working out the details, but I think I see a way to create a read-only outbound area for instructors and a write-only inbound area for students to turn things in. By saving students turned in work with uuids in the filenames, we can prevent other students from overwriting each others work, and can also have a full auditable record of each time a student submits something (usually we will just grade the last one).

Here is the rough flow (assuming the usernames are instructor and student1, student2):

To distribute an assignment directory homework1 to students:

    nbgrader push homework1 instructor.phys202-2015.homework1

To grab this assignment, students would do:

    nbgrader pull instructor.phys202-2015.homework1

To turn their work in, students would do:

    nbgrader push homework1 instructor.phys202-2015.homework1

To get all students work, instructor would do:

    nbgrader pull instructor.phys202-2015.homework1

This extremely terse syntax assumes that nbgrader push/pull will be run as the instructor/student user. It also assumes that the unix usernames match the nbgrader usernames, but I think that could be relaxed easily. I will be building this today and submit a PR, but I have to have this working by tomorrow so I may just go ahead and merge the PR when it is in good shape and we can iterate in master.

**Comment by jhamrick** [comment]
Would this essentially replace the functionality of `nbgrader submit`?

In your examples, e.g. `nbgrader push homework1 instructor.phys202-2015.homework1`, is `homework1` the name of a directory in the current working directory, and `instructor.phys202-2015.homework1` is a directory in `/srv/nbgrader/exchange`? Since the `pull` and `push` commands are identical, how would nbgrader know that it should be submitting an assignment vs. releasing an assignment, or downloading just the release version of an assignment vs. downloading all submitted assignments?
