### ISSUE TITLE
Skip extra notebooks

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#258]
Right now if a student puts an extra notebook in their assignment folder, things won't work. We should just skip all the extra notebooks students add.

**Comment by jhamrick** [comment]
Ahh, hmm, yes. I have my own custom code that deletes extra files (any that aren't present in the source directory), but I didn't add it to nbgrader because there are cases where you wouldn't want this (e.g. if students are allowed to add their own helper files, or are told to save out a data file, etc.). Having it simply skip extra notebook files would work well I think, though, without getting into the details of figuring out what is ok to delete and what isn't.

**Comment by ellisonbg** [comment]
I wrote similar code just now to delete those extra files, but it would
definitely trip people up in the long run..

On Wed, May 6, 2015 at 1:05 PM, Jessica B. Hamrick <notifications@github.com
> wrote:

> Ahh, hmm, yes. I have my own custom code that deletes extra files (any
> that aren't present in the source directory), but I didn't add it to
> nbgrader because there are cases where you wouldn't want this (e.g. if
> students are allowed to add their own helper files, or are told to save out
> a data file, etc.). Having it simply skip extra notebook files would work
> well I think, though, without getting into the details of figuring out what
> is ok to delete and what isn't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/258#issuecomment-99589408>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
