### ISSUE TITLE
Give a more informative error message for missing notebooks

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#260]
If a student deletes a notebook, then the grader gives a 404 error when trying to access it. It would be good if:

1. There was a warning in place to help prevent students from submitting assignments with missing notebooks (maybe there is already?).
2. The keyboard navigation skipped missing notebooks.

**Comment by jhamrick** [comment]
1 would be nice, but would be hard to given the current setup of nbgrader, because the students don't (and shouldn't) have access to the database where grades/assignments/etc. are stored.

2 is definitely doable, and if the submissions is clicked directly, it should give a better error message, something like "the student did not submit this notebook".
