### ISSUE TITLE
Simplify naming of directories and files in documentation

### ISSUE THREAD

**Issue by willingc** [jupyter/nbgrader#333]
The current documentation uses "Problem Set 1" and "Problem 1" as file and folder names. These names include spaces which can be problematic on different operating systems. It may be worthwhile in a future release to refactor these names to remove the spaces.

For example, "Problem Set 1" becomes "ProblemSet1" or "Problem_Set_1" or "ProblemSet_01".

The documentation style could also use uppercase for folders "ProblemSet_01" and lowercase for files "problem_01.ipynb".

**Comment by jhamrick** [comment]
Yeah, I'm kind of torn about this. On the one hand, it's nicer from the notebook list to have files that have spaces because they're easier to read, but the downside is exactly what you've pointed out. Maybe for the official examples though it's better to do it without spaces so that the demos are easier for people to work with.

**Comment by jhamrick** [comment]
I want to think about this a bit further so I'm going to mark this for the next release, but it's definitely something that should be addressed.

**Comment by willingc** [comment]
@jhamrick Good point re: the notebook list. I didn't realize that the file and folder names flowed directly into the user interface. I agree that this is something for the future. Probably would be good to consider include character languages such as Japanese and Mandarin and unicode too.
