### ISSUE TITLE
Hide autograder test cells

### ISSUE THREAD

**Issue by dementrock** [jupyter/nbgrader#390]
Is it possible to have the autograder test cells hidden for the release notebook? If not, where in the code should I change to make this possible?

**Comment by jhamrick** [comment]
No, unfortunately, it's not possible to do that at this time because there
is no way to hide cells in the notebook itself. One possibility that might
work is to introduce another special syntax for selectively removing some
tests (eg '### BEGIN TEST' and '### END TEST') kind of how there is for
solutions, but this would still require you to include *some* tests so that
students don't just see a bunch of blank cells.

On Saturday, August 29, 2015, dementrock <notifications@github.com> wrote:

> Is it possible to have the autograder test cells hidden for the release
> notebook? If not, where in the code should I change to make this possible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/390>.
>


-- 
Cheers,
Jess

**Comment by hkarl** [comment]
I'm facing the same issue...  Let's assume we are content with having autograder cells in the released notebook and just want to remove some of the tests in each cell. 
 
From what I understand so far, there are various options: 

1. Simple and ugly: post-process the files in release/../*.ipynb by a "sed s/..//g " and remove all content between marker lines. Should work nicely, but clearly not elegant. 
2. Try to fiddle with the Preprocessors, but that does not seem trivial as AssignApp first calls ComputeChecksum and then SaveCell. When stripping content after SaveCell, we would have to recompute Checksums, it seems? Else, a final Preprocessor in this chain shouldn't be difficult to write. 
2. Subclass FilesWriter and use a new class instead that strips out all tests between marker lines. That's perhaps the cleanest solution. I'm trying this, but stumbling across nbconvert issues (needs checking, see https://github.com/CN-UPB/nbgrader/blob/master/nbgrader/writers/nbgraderwriter.py ). 

I'd appreciate any pointers here; what do you think is the most promising approach? 

Thanks a lot, 

Holger

**Comment by jhamrick** [comment]
Yes, the tricky part is definitely going to be making sure that validation doesn't break. Your second suggestion (using preprocessors) is the way I would do it. Your proof-of-concept I think is on the right track, and I like the idea of having two separate checksums -- that's cleaner I think than the way I was originally thinking of doing it, which was actually adding a new field into the database for the cell contents with and without hidden tests.

**Comment by hkarl** [comment]
Thanks for the thumbs up. I've added a bit more code to my little PoC. Actually, I think it does work with very little code; there is no need to do anything but the (next to trivial) Preprocessor to remove the undesired lines and put a new checksum into the cell. Later, after submission, the autograder will detect the incorrect checksum and replace it with the original content of the cell anyway - so that's just the desired behavior. 

I do beg forgiveness for a few more questions (I am just not to familiar with the various frameworks used here): 

* Commit https://github.com/CN-UPB/nbgrader/commit/70ed418ee6ade5c4cad246b034bed2710551595c tries to make the start / stop marker lines configurable. They don't show up in the config file via quickstart? 

* Commit 
https://github.com/CN-UPB/nbgrader/commit/bc43a6746d4d25370a4933d026d5b79697d3ac0b  tries to come up with a first test. I am confused by the test framework a bit, so this one is based on the assign test. Hence, it struggles with new /srv/... exchange file, runs as the local user, and some other oddities. Would it make more sense to base it on the auograder (e.g.) test case? But then, don't we run into a problem since we don't have the data base? 

Again, sorry for these likely stupid questions and taking up your time. Thanks a lot for nbgrader in general!

**Comment by huwf** [comment]
I also came up against this.  A workaround I'm thinking about for now, is to import the  publicly visible tests from a `tests.py` file, and within that file use a try/except block to import "hidden" tests in a folder the students don't have access to.  Not properly tested yet, but I feel like it "should" work. https://gist.github.com/huwf/453349c4a66d64ebcd92da031b44f7e4

**Comment by hkarl** [comment]
Hi, 

interesting idea. I hope to be able to turn my proposal into a pull request soon; it seems to work fine, just needs more test cases. 

best, 

Holger

**Comment by jhamrick** [comment]
> Commit CN-UPB@70ed418 tries to make the start / stop marker lines configurable. They don't show up in the config file via quickstart?

You'll need to add the preprocessor to the `__all__` variable in `nbgrader/preprocessors/__init__.py`, I believe.

> Commit 
CN-UPB@bc43a67 tries to come up with a first test. I am confused by the test framework a bit, so this one is based on the assign test. Hence, it struggles with new /srv/... exchange file, runs as the local user, and some other oddities. Would it make more sense to base it on the auograder (e.g.) test case? But then, don't we run into a problem since we don't have the data base?

It probably makes sense to have tests both for `nbgrader assign` (to ensure the tests are removed correctly) as well as `nbgrader autograde` (to make sure that they get inserted back in) and also `nbgrader validate` (to make sure that validation isn't broken for students).

Both the `nbgrader assign` and `nbgrader autograde` test cases should create the database automatically -- the `db` variable that shows up in the test function signatures is a [pytest fixture](http://doc.pytest.org/en/latest/fixture.html) which gets created automatically before each test is run. You will need to *populate* the database though, which you can do by running `nbgrader assign` first.

**Comment by lgpage** [comment]
>I hope to be able to turn my proposal into a pull request soon; it seems to work fine, just needs more test cases.

@hkarl an progress with this?

**Comment by hkarl** [comment]
Hi,

well - we have this in production use. No problems with it. I just didn't have time to look into the test cases, etc.

Jonas has the job to do that, but I am not sure when he get around to officially document it.

best,

Holger


> On 23 Jan 2017, at 14:51, Logan Page <notifications@github.com> wrote:
> 
> I hope to be able to turn my proposal into a pull request soon; it seems to work fine, just needs more test cases.
> 
> @hkarl an progress with this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Prof. Dr. Holger Karl
Computer Networks group - http://wwwcs.upb.de/cs/cn/

Please send email, do not call me!

Need to talk to me? -  http://tinyurl.com/k2qht4w

--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

OAN: https://www.facebook.com/timothy.david.snyder/posts/1206636702716110

**Comment by lgpage** [comment]
@hkarl would you mind if I picked up with where you left off? I would love to get this feature into ``nbgrader`` before my classes start :smile:

**Comment by hkarl** [comment]
@lgpage Sure. Not sure what the best way would be to give you access to our code? a pull request here seems premature. Maybe coordinate via email (hkarl@ieee.org) ?
