### ISSUE TITLE
Create Assignment toolbar not rendering right in safari

### ISSUE THREAD

**Issue by jonathanmorgan** [jupyter/nbgrader#394]
The Create Assignment toolbar is not rendering right in safari at the moment.
![screen shot 2015-08-29 at 5 37 19 pm](https://cloud.githubusercontent.com/assets/490745/9564552/c66ed45c-4e78-11e5-9e54-5879db5b5048.png)

**Comment by jhamrick** [comment]
Sigh, ok, so this is because of the following CSS:

```
div.lock-cell-container {
    margin-right: auto;
}
```

which on Chrome and Firefox is handled properly (i.e. it doesn't cause the rest of the elements to get pushed outside of the `celltoolbar` parent) but on Safari it's apparently not calculated the same way. Looking at the CSS in the Safari developer tools, I *think* this is because Safari seems to be using `display: -webkit-box` for the `celltoolbar` parent rather `display: flex`.

I don't know enough about the details of CSS to know how to make it work both for `-webkit-box` and `flex`... @Carreau would you know the answer to this? Or if not do you know who might?

**Comment by Carreau** [comment]
Acknowledge being mentioned. Assigning myself.

**Comment by Carreau** [comment]
`https://github.com/jdfreder/jupyter.github.io/blob/camerons/css/logo-nav.css#L303` lonely dot.

**Comment by jhamrick** [comment]
@Carreau did you mean to leave that last comment on a different issue?

**Comment by Carreau** [comment]
Rhaa... thanks sorry. Multi tabs and tired.

**Comment by Carreau** [comment]
Of course this is a general flex-box issue on safari for which the right fix looks like that:

<img width="846" alt="screen shot 2015-08-31 at 19 12 15" src="https://cloud.githubusercontent.com/assets/335567/9584924/3e3deeea-5014-11e5-807b-5fb3e838cbb3.png">

**Comment by jhamrick** [comment]
Bleargh, css is the worst.

**Comment by Carreau** [comment]
You are using `the worst` a lot ;-)

**Comment by jonathanmorgan** [comment]
works fine in 0.2.2.
