### ISSUE TITLE
nbextension: Don't force cells to have id's

### ISSUE THREAD

**Issue by jklymak** [jupyter/nbgrader#403]
Hi, I'm basically just using nbgrader to make a bunch of manually graded questions followed by answer cells.  I can "assign --no-db" and not have nbgrader care about whether I have added a grade or not (great!).  However, if I don't give my cell "ID"s I can't save my notebook ("Invalid nbgrader cell ID").  It seems to me that this should be an error at the "nbgrader assign" stage, *not* at the editing stage, and that it should be ignored if we do "assign --no-db".

FWIW, I don't think this "error" really stops the notebook from being saved, but it is pretty annoying.

**Comment by jhamrick** [comment]
Hmmm, that's tricky, as it's really useful to be notified while you're creating the assignment if you're missing stuff... I specifically added that in because otherwise other people working on assignments for our class would forget, and then I'd have to go fix it myself when I went to release the assignments. So have it warn you in the notebook itself removes a fairly big burden from whoever is in charge of releasing assignments when you have multiple people creating them.

Are you just using nbgrader for creating the student version of an assignment? Or are you planning on doing grading with the formgrader too?

**Comment by jklymak** [comment]
I just want a way to identify cells as "only include in the key". nbgrader is a bit of a sledgehammer to crush a walnut, but no other walnut opening tools appear to be readily available.   So was using "Read-only" and "manually graded" to do that, using "nbgrader assign" to put in the release directory and making that available to students.  I'll copy the key in manually after the due date.  

For my purposes I just commented out the "check ids" in the save hook in main.js, and it works fine.  

If there were a more lightweight way to attach meta data to cells, and then search and replace on the metadata to clear the cell for release that would be even better.  But, if I have a sledgehammer, and I don't have time to make a nutcracker, I guess the sledgehammer will have to do...

**Comment by jhamrick** [comment]
Aha, ok, thanks for explaining -- that helps! Here's what I'd suggest:

1. Don't actually use the "Create Assignment" toolbar. Instead, just write the `### BEGIN SOLUTION` and `### END SOLUTION` syntax to denote your solution regions.
2. Currently the `ClearSolutions` preprocessor will complain if you haven't marked the cell as a solution cell, but I can add a configurable option to it to disable that.

So, if you disabled that option, then you would be able to create your assignments using the solution regions (but not any of the other nbgrader metadata that the toolbar adds) and then be able to run `nbgrader assign` and have it clear those regions. Does that sound like it would work for you?
