### ISSUE TITLE
Skip failed notebooks during autograding

### ISSUE THREAD

**Issue by joschu** [jupyter/nbgrader#416]
When I type ``nbgrader autograde hw1``, about 10% of the homeworks fail for some miscellaneous reason, and the autograding script terminates. It would be good if it would just continue and print out a report at the end of which students it failed for, then I could grade those manually.

**Comment by jhamrick** [comment]
Hmm, if it's failing on the autograde step, then it's probably a bug. What error messages does it give when it fails?

**Comment by joschu** [comment]
All the problems turned out to be due to two causes:
1. students had renamed the ipynb file (that's easy to fix, and not nbgrader's fault)
2. their notebooks were using python3, whereas the grading was running under python2

**Comment by jhamrick** [comment]
Hmm, yeah, the first one isn't really something nbgrader can handle, the second one I could try to make sure they get run with the same kernel that they were released with. In general it would probably be good if it saved out a log file or something, so that you could regrade failed submissions later.

**Comment by mandli** [comment]
I have gotten around this by running through the API and catching the exception raised.  Would be nice to have something similar on the command line (second on the enhancement).
