### ISSUE TITLE
Disappearing Meta-Data From Manually Graded Cells

### ISSUE THREAD

**Issue by mandli** [jupyter/nbgrader#424]
This may be more of an instructional problem but my grader and I have been trying to confirm a problem we have been seeing where notebooks that have turned in are missing the nbgrader meta-data from some of the manually graded cells.  My ongoing assumption is that the students deleted and repopulated a cell with the same information (without the meta-data) but the students I have talked to seem to not think this is the case (for what that's worth).  

Is this something that someone else has experienced?
Is there a work around beyond re-entering the meta-data back in manually?

**Comment by jhamrick** [comment]
Hmm, that's certainly a possibility. Can you post 1) the metadata of the cell in the version of the assignment produced by `nbgrader assign`, and 2) the metadata of the cell in the assignment they turned in?

**Comment by mandli** [comment]
An example cell from `nbgrader assign`
```json
 {
   "cell_type": "markdown",
   "metadata": {
    "deletable": false,
    "nbgrader": {
     "checksum": "f49a7e24f3177290dc54b8e4342edc99",
     "grade": true,
     "grade_id": "A-1a",
     "locked": false,
     "points": 1,
     "solution": true
    }
   }
```
and the student's notebook has an empty meta-data dictionary for the same cell (at least in the order it should be in).  Honestly I find it hard to believe the student did not just delete the cell.  If a student does delete a cell, how does `nbgrader` decide how to add back those cells?

**Comment by jhamrick** [comment]
Hrm. If that's the metadata after running `nbgrader assign`, then I'm tempted to believe that the students didn't delete the cell -- you'll notice that there is a `"deletable": false` entry in the metadata, which prevents the notebook from deleting that cell. So unless they went in and modified the metadata manually, and *then* deleted the cell, it shouldn't be possible for the cell to be deleted.

Just to double check though, could you try deleting that cell yourself (from the version that students get)? If that works, then that's definitely a problem... if not, then I'm not sure what would be going on. Would you be willing to email me a copy of the original notebook, the one produced by `nbgrader assign`, and the (anonymized) student's notebook?

nbgrader doesn't add back in cells, which is why it marks them as undeletable, which should prevent the issue of having students delete cells with important metadata and then recreate them from a blank cell (which would from their perspective be a completely reasonable thing to do, but which would break nbgrader).

**Comment by mandli** [comment]
Hmm, I cennot delete it.  I will send you the student's notebook and the released version.

**Comment by jhamrick** [comment]
Aha -- I think I know what happened! Thanks for sending the notebooks. It seems like the student is running an old version of the notebook, as their notebook has been submitted using nbformat 3 (which was used prior to ipython 3.x), whereas your released version is nbformat 4 (which was introduced in ipython 3.x). If I remember correctly, I believe that the feature for making cells undeletable was introduced in ipython 3.x -- meaning that for the older version of the notebook, it just ignores that piece of metadata and allows any cell to be deleted.

So, yes, I do think that the student must have accidentally deleted the cell since their version of the notebook must have allowed them to, and then recreated it in a new cell. Unfortunately, I don't think there's anything I can really do to detect that in nbgrader, since nbgrader doesn't actually run on students' systems. 

I would say for the current assignment, you'll have to (unfortunately) fix the metadata manually so that nbgrader will run, and ask your student to update to a more recent version of the notebook (at least 3.x). If you wanted to prevent this in the future, you could add a test case to your assignments along the following lines:

```
import IPython
assert IPython.version_info[0] >= 3, "Your version of IPython is too old, please update it."
```

**Comment by jhamrick** [comment]
Actually, reopening this, as I would like to add something in the documentation letting other instructors know that they should make sure their students have at least version 3.x of the notebook installed.

**Comment by mandli** [comment]
Ah, makes sense, thanks for figuring that out!
