### ISSUE TITLE
'Timeout waiting for IOPub output': dead kernel have to cancel notebook grading

### ISSUE THREAD

**Issue by ischurov** [jupyter/nbgrader#427]
I'm autograding a notebook with a cell that contains incorrect solution with infinite loop. As it is infinite, after timeout (30 seconds by default) nbconvert tries to interrupt kernel (emulates KeyboardInterrupt exception). Normally it works fine: kernel gets KeyboardInterrupt and the corresponding test fails (and is marked as failed), then we continue with other cells. However, it seems that if the infinite loop also memory consuming (think `while True: some_list.append(1)`), kernel sometimes freezes and does not respond on KeyboardInterrupt (actually, we see this behaviour from time to time using Jupyter Notebook interactively, when Interrupt Kernel doesn't work and we have to restart kernel). Then we have a warning: `Timeout waiting for IOPub output`. No exception is recorded into the notebook output and the corresponding test is not marked as failed. After that, we are trying to execute the following cells. But the kernel doesn't respond (it seems it is actually dead), and after timeout we again does not record the exception. Finally, we see that no cells gave us exceptions and mark all test as passed, which is definitely wrong.

I believe that we have to process this situation in the following way: if we have `Timeout waiting for IOPub output`, then we decide that something goes fundamentally wrong and mark all the notebook as not-graded.

Is it possible to do this? Is it possible to tell nbconvert to give up after the first `Timeout waiting for IOPub output` and not waste time trying to connect to the dead kernel?

**Comment by jhamrick** [comment]
Hmm, interesting. I'm tempted to say this is actually something that should be fixed in the `ExecutePreprocessor` in nbconvert, but we can try to fix it in nbgrader first and then port the fix to nbconvert.

Anyway, I definitely think it should be possible to fix this -- the relevant part of the code is here:

https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L153

The thing I don't know is if there are cases when there is an iopub timeout that's ok, i.e. should an error always be raised if there is an iopub timeout or should that be a configurable option? Maybe @minrk knows?

Unfortunately I won't have time right away to look into this further. If you want to try to make a PR with a fix that would be awesome, otherwise I'll try to get to this in a week or so.

**Comment by minrk** [comment]
I think it's reasonable to treat IOPub timeout as something went wrong. It's mainly there to prevent hanging forever.

**Comment by jhamrick** [comment]
I have opened a PR for this in nbconvert. Once that is merged, and after the next release of nbconvert, I will update the execute preprocessor in nbgrader accordingly.

**Comment by ElectricGizmo** [comment]
I do have the same "Timeout waiting for IOPub output" when rendering to html using nbconvert.
It appears that it is simply due to the processing in the script I invoke to be too long - when running the notebook interactively (i.e. in Jupyter) it does take time but it performs as expected.

Is there a simple way to extend the timeout?
Thanks
