### ISSUE TITLE
Improve security by running autograder in isolation

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#483]
Perhaps this could be done in Docker containers? Or maybe just a chroot would work?

**Comment by huwf** [comment]
I looked into running `nbgrader autograde` in a Docker container.  This isolated it from other files on the system, but I still had to mount `gradebook.db`, which the assessment could presumably write to since was run by the instructor which we don't really want.  A different kind of security, but we don't want students to be able to change their grade! :)

Which part runs the student's code,  I wasn't able to figure that out?  If I can separate that, then I could run it in a container and return the result to then update the `gradebook.db` on the host.  I'll see how I can integrate this better into the nbgrader code.  I'm running as a cron job at the moment

A bit convoluted probably and not properly tested, but here's my code.  And TBH I can hardly even remember what it does.  Too much work!:

    p = subprocess.Popen([ 'docker', 'run', '-dt', '--rm'
       '-v', '%s:/home/instructor/user-submission/' % (submitted_path),
       # I need to be able to autograde without having the whole autograde directory,
       # but only want to mount on one directory
       # This is a temporary directory.  In autograde.sh we will run:
       # cp -R autograded/username/assignment_name/* autograded-docker
       '-v', '%s:/home/instructor/autograded-docker' % (autograde_path),
       '-v', '%s/gradebook.db:/home/instructor/gradebook.db' % dirpath,
       '-v', '%s/nbgrader_config.py:/home/instructor/nbgrader_config.py' % dirpath,
       '-v', '%s/students.txt:/home/instructor/students.txt' % dirpath,
       'nbgrader-container-admin',
       '/autograde', username, assignment_name, str(instructor_id)])

Dockerfile

	FROM python:3.5.2-slim

	RUN python3 -m pip install nbgrader
	RUN python3 -m pip install pymongo
	RUN python3 -m pip install nose

	RUN useradd -ms /bin/bash instructor

	RUN nbgrader extension install --symlink --debug
	RUN nbgrader extension activate

	WORKDIR /home/instructor

	RUN mkdir -p /home/instructor/submitted
	RUN mkdir /home/instructor/autograded
        # Maybe we could auto generate and build Dockerfile rather than hardcoding
	RUN mkdir -p /home/instructor/source/assignment_name

	# Folders for mounting...
	RUN mkdir -p /home/instructor/user-submission
	RUN mkdir -p /home/instructor/autograded-docker

	RUN touch .nbgrader.log
	RUN mkdir .jupyter

	ADD autograde.sh /autograde
	RUN chmod 755 /autograde

autograde.sh (runs on Docker container load)

        #!/usr/bin/env bash
	# Parameter 1: name of the user
	# Parameter 2: name of the assessment
	# Parameter 3: ID of the instructor user on the host to chown back
	cd /home/instructor
	#mkdir -p /home/instructor/submitted/${1}/${2}
	#mkdir -p /home/instructor/autograded-docker/${1}/${2}
	echo "user-submission: $(ls -al user-submission)"
	#echo "autograded: $(ls -al autograded)"

	#ls /home/instructor/autograded/${1}/${2}
	#echo "
	#mv /home/instructor/autograded/${1}/${2}/* /home/instructor/autograded-docker/${1}/${2}
	mkdir /home/instructor/submitted/${1}

	cp -R /home/instructor/user-submission/* /home/instructor/submitted/${1}
	echo "submitted again: $(ls -al submitted)"
	nbgrader autograde ${2}
	echo "autograded $(ls -al autograded)"
	echo "autograded-docker $(ls -al autograded-docker)"
	mv autograded/${1}/* autograded-docker/
	chown -R ${3}:${3} .

**Comment by huwf** [comment]
Although note I don't think Docker considers its isolation as a security feature, although that may have changed due to the increased security which containers now offer.  Probably better than nothing, and more secure than not doing this provided we limit the permissions.  I think it would probably be acceptable for semi-trusted users

**Comment by jhamrick** [comment]
This is awesome!

I think to fully address the issue of the gradebook being accessible by the student, we will need to do something like shelling out to docker *only* for the execution part, then have that return a JSON string with the results or something, and then have the parent process update the database. That is getting pretty complicated, though, and I think something like what you have here is really important even if there is still that vulnerability.

The actual execution comes from the `Execute` preprocessor, which inherits from the `ExecutePreprocessor` in `nbconvert`: 

* https://github.com/jupyter/nbgrader/blob/master/nbgrader/preprocessors/execute.py
* https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py

I wonder if we could build this into nbgrader by doing something like the following:

1. Host something like your docker file on docker hub
2. Add a `--docker` flag to `nbgrader autograde` (i.e. `nbgrader autograde --docker`)
3. When the `--docker` flag is used, nbgrader pulls the image from github and executes essentially the command you gave above, rather than doing its normal autograding thing.

**Comment by huwf** [comment]
Glad you like it! :)  

I noticed a couple of minor bugs in that which I have since corrected in my code somewhere.  I'll create a GitHub repo when I get a chance and test it a bit better for which you are welcome to use the code from.  Or the code in this thread as well of course :)

I think the way you describe is the way to integrate it.  Only issue is that it might be tricky to concisely set up the container with the correct options without adding a load of parameters.  Though I guess these could be added to the `nbgrader_config.py` maybe?

I think we could trust people to only use the `--docker` flag if they had Docker installed!  It shouldn't be a very big image, are there any current conventions are about including a dependency for a Docker container in code?

For the `gradebook.db` vulnerability, thinking about it, we would not actually need to worry about executing as a different user.  If we subclassed `Execute` so that it writes to a JSON file as well, we just mount a file `output.json` to the container to read from, and mount a fake `gradebook.db` to the container it can write to which we can then ignore.

**Comment by jhamrick** [comment]
> I noticed a couple of minor bugs in that which I have since corrected in my code somewhere. I'll create a GitHub repo when I get a chance and test it a bit better for which you are welcome to use the code from. Or the code in this thread as well of course :)

Cool, thanks!

> I think the way you describe is the way to integrate it. Only issue is that it might be tricky to concisely set up the container with the correct options without adding a load of parameters. Though I guess these could be added to the nbgrader_config.py maybe?

Yeah, I think it should be fine to add them to the nbgrader config. We can just make sure to document the options really well, e.g. adding an entirely new page of documentation explaining how to use it with docker or something.

> I think we could trust people to only use the --docker flag if they had Docker installed! It shouldn't be a very big image, are there any current conventions are about including a dependency for a Docker container in code?

Yes, agreed. I think we can check if the `docker` command exists and if it doesn't print out a helpful error message saying it needs to be installed.

I don't know about any conventions for including docker as a dependency. I think it's fine if we don't include it as a dependency and just let people know if they have it installed then they can use this feature.

**Comment by gertingold** [comment]
@jhamrick: congratulations on successfully closing #141!

Motivated by security concerns voiced after a [Jupyterhub/nbgrader presentation](https://github.com/gertingold/lit2018), I looked a bit into the issue discussed above. It seems that it could be helpful to split the work done by `autograde` into three steps.  It would then be sufficient to only make the `autograded` directory accessible to docker. In particular, access to `gradebook.db` is not needed during execution of the notebook, thereby avoiding the possibility to spy out grades or to manipulate them.

`autograde` is already performing its work in two steps defined by the lists `sanitize_preprocessors` and `autograde_preprocessors`. After having sanitized the notebook taken from the `submitted` directory, the result is stored in the `autograded` directory. During this first step, no notebooks are executed and thus dockerization is unnecessary. As a consequence, there is no need to grant to docker access to the `submitted` directory.

The first preprocessor in `autograde_preprocessors` is `Execute` which actually executes the notebook but does not need access to `gradebook.db`. Therefore, it is only this step which needs to be executed within a docker environment (or possibly chroot). 

The third preprocessor in `autograde_preprocessors` is `SaveAutoGrades` which determines the grades and saves them to `gradebook.db`. It does so on the basis of `output.output_type` in the metadata of the executed notebook. Thus, the grades are already exported via JSON and no extra mechanism is needed to isolate `gradebook.db` from harmful code.

I would therefore propose to essentially split `autograde` into three steps:
1. Sanitizing by means of the preprocessors specified in `sanitize_preprocessors`.
1. Apply preprocessor `Execute` in a docker environment.
1. Apply the preprocessors specified in `autograde_preprocessors[1:]`.

In the second step, one could follow the recipe proposed by @huwf in an adapted form, i.e. without giving the docker container access to the `submitted` directory and to `gradebook.db`. I am wondering whether it would also be an option to have a dockerized python kernel for Jupyter. Then, `Execute` would just have to ask for the dockerized kernel, if available. 

One could imagine having a flag which asks `autograde` to execute one of the three steps. Then, the idea of @huwf could easily be adapted. Of course, if the flag is not present, `autograde` should work as before.

Do these ideas make sense? If yes, I could try to work on an implementation.

**Comment by gertingold** [comment]
Having three subcommands sounds like a very good idea. I'll try to work on an implementation.

**Comment by gertingold** [comment]
As an update of what I have been trying to do so far: Looking at the code, it seemed quite easy to implement three options `--only-sanitize`, `--only-execute`, and `--only-record` very much in the spirit of the `--no-execute`-flag, i.e. by disabling certain processors. However, it turned out that for the options `--only-execute` and `--only-record`, I needed to specify `--force` as well, because otherwise the assignment would be considered as already autograded. However, there might be side effects which I have not thought of. Any comments in this direction are welcome. May be in the end, implementing subcommands is indeed the way to go and I will look into that if what I have been doing so far does not work as intended.

**Comment by jhamrick** [comment]
Hmm, it depends a little on how you've implemented it, but usually what happens with  `--force` is that it will cause files to be deleted from the `autograded` directory. So if you use `--force` with `--only-record`, it may delete those files and re-copy them, which would be a problem then because then it will be determining grades based on notebooks that haven't been executed yet.

If you want to make a work-in-progress PR I can try to provide some more detailed feedback!

**Comment by rkdarst** [comment]
Hi,

I'm working on setting up nbgrader for our university, and security here seems to be the only major flaw.  Our first course is quite large, and it seems that checking notebooks for security manually isn't a viable option.  And making nbgrader depend on docker seems quite complex (we are running on kubernetes... so having containers in containers, with related permissions management for semi-trusted instructors and students seems like overkill).

So... I was thinking about what the options were.  I was thinking something quite along these lines by @gertingold: "I am wondering whether it would also be an option to have a dockerized python kernel for Jupyter".  Really, docker doesn't seem necessary, only a kernel which has more restricted permissions somehow.  (Is this correct?)  This line of thinking was inspired by the different "restricted pythons" which are said to not work.

  Because I had to deal with them recently, I know that Linux has namespaces support (as docker uses internally, from what I know).  This provides the ability to have a process see different mount paths, users, etc.  (for us, most important is probably a different filesystem).  I read that Chrome does something similar, but I haven't found any details.

So, could we basically...
- Have an autograde option to "run autograde notebooks with a different kernel"
  - Which allows us to insert a dockerized kernel anyway.  Isn't this easier than first-order docker awareness in nbgrader?
- Create a wrapper which can run a kernel in a separate mount namespace with only limited paths available (bin,lib,opt, etc - mainly everything except the instructor home).

As a proof of concept, I have been experimenting and made an initial script.  It is pure userspace, no extra permissions needed.  (Also my knowledge of these concepts is very limited... it would be better if this was re-done by someone who knows what they are doing)  It roughly:
* `unshare --user --map-root-user --mount-proc --pid --fork` - make new namespace.  You appear to be root inside, but actually you are your user
* `mount --bind /bin $DIR/bin` - and so on for everything that should be accessible inside
* `chroot $DIR $@`
* It's actually more fancy because it uses pivot_root, and could do more, but I haven't got all the bugs worked out yet.

This is in fact replicating container mechanisms, but only what is needed to deny access to the instructor's files.  Maybe there is a simpler way to do this via a separate kernel - like my original idea of a restricted python.  As I have said, someone who is an expert in containers/namespaces should look at this and let us know the simplest way to get process isolation.  I bet there are some utilities that would do this already, but I haven't found them.

Glaring bug: it seems that this doesn't work inside of an already existing container, which might mean it ends up being useless to me.  Though I bet someone can solve this because there are reports of containers in containers.  This would also affect the docker implementation, and require the instructor kube to be able to start other kubes, which would turn into its own security considerations.


What do you think?

**Comment by rkdarst** [comment]
OK, I worked on this some and my results are in this repository.  The proof of concepts works, and I was able to execute the notebook within a protected kernel.  It required no changes to nbgrader, just make a new kernel and use the option `--ExecutePreprocessor.kernel_name=python3-isolated`.  It works as a normal user on modern Linux with no root required.  However, it doesn't work within an existing container yet.

My code and instructions to use with nbgrader are in https://github.com/AaltoScienceIT/isolate-namespace .  Instructions are somewhat oriented to my university's use so far.

How it works:

Copy your existing `python3/kernel.json` and make a new one `python3-isolated/kernel.json`.  Change the `argv` to prepend a few things: `"argv": ["isolate.sh", "--mnt", ". /work/modules/ {connection_file} /l/darstr1/conda", "--no-net", "--", "/l/darstr1/conda/bin/python","-m", "ipykernel_launcher","-f","{connection_file}" ]`.  The key argument is `--mnt`: which files and directories will be bind-mounted inside the isolated environment.

All this does is use `isolate.sh` as a wrapper.  nbgrader already does `chdir` into the notebook's directory before executing, so you just have to share `"."` inside the new namespace. Unless you use external files, this is all you need - no need to split autograde into three parts.  In my command above, I also mounted some conda directories to let my desired Python interpreter work.

What does `isolate.sh` do?  As far as I can tell, basically the same mechanics that containerization does: create tmpfs, bind mount a bunch of stuff, chroot into it, run desired command.  I'm *not* a container expert but it works.

What do you think?

p.s. But... note that all of the same mechanics can work for a docker based solution without any nbgrader modifications.  Make a new kernel, add some `argv` wrapping that calls `docker run` with the right arguments to wrap the kernel.  Is splitting into three parts really needed?  To make it even easier, we could make  a way to prepend arbitrary options to the Jupyter kernel argv from nbgrader - this manual making of a new kernel is kind of hackish.

**Comment by rkdarst** [comment]
There are other examples of editing the kernel to run in containers:
- https://groups.google.com/forum/#!topic/jupyter/kQ9ZDX4rDEE
- https://github.com/clemsonciti/singularity-in-jupyter-notebook (singularity doesn't require or give root except for installation)

These combined with `--ExecutePreprocessor.kernel_name=python3-isolated` would achieve isolation, right?

**Comment by jhamrick** [comment]
@rkdarst This is great. Honestly, I think the less we have to modify about nbgrader to get this to work, the better... so I love the idea of using a restricted kernel. Do you think the isolate script works with other kernel types as well? i.e. do you think it would be straightforward to maybe do something like create a little command that wraps an arbitrary kernel (python, ruby, javascript, ...) and creates a secure version of it that nbgrader can then use? I'm envisioning something like:

```
$ nbgrader secure-kernel python3
Creating secure kernel... done!
Please add the following line to your nbgrader_config.py to use this kernel:
    c.ExecutePreprocessor.kernel_name = "python3-isolated"
```

Were you ever able to get your script working inside an existing container?

@kcarnold thanks for the pointer!

**Comment by rkdarst** [comment]
The isolate script *should* work as long as you can whitelist certain paths to pass in.  It might be hard to find what they are (I want to add an option to infer them from PYTHONPATH, could be same for other languages).  (I'm still not sure if I'm pleased or disgusted by `isolate.sh` - I liked making it, but I'd wish there is something with better support.)

I think my favonite way would be to add a `--kernel-command-prefix` option that could prepend something to the kernel path.  It would be, for example, `--kernel-command-prefix=["isolate.sh", "--mnt", ". /work/modules/ {connection_file} /l/darstr1/conda", "--no-net", "--"]`.  But this would require support in at least one other package, and could easily be seen as a layering violation.   But... the secure kernel creation command could take this argument for us!  It wolud be nice to make it usable for more than nbgrader.  We can easily make something that can be have many different isolators plugged into it, so I like this idea.

As for docker, unfortunately I haven't tried yet (but it would be more elegant than `isolate.sh`, but require more other stuff installed).  I do know more about docker than before, though, and I think the biggest issue is that you have to expose a port via command line, and you don't know what that port will be in advance.  A wrapper script could parse the kernel file and expose the proper port.  You'd have to mount `.` and use that, but should be possible.

**Comment by rkdarst** [comment]
I wrote a wrapper script to run a kernel (only) in a docker container.  This should be suitable for autograding securely,  but is alpha (seems like it should work but probably deserves a rewrite).

https://github.com/AaltoScienceIT/jupyter-docker-kernel

Usage:

Install the new kernel with the name `python3secure`, using the given image:
```
./jupyter_docker_kernel.py setup --user --name=python3secure --image=aaltoscienceit/notebook-server:0.5.9
```

Run autograding using this new kernel:
```
nbgrader autograde --ExecutePreprocessor.kernel_name=python3secure
```

There are options to adjust mounts and so on.  The working dir is automatically mounted, but note that i/o is not necessarily even needed inside the container since the code goes to the kernel over the kernel network connections.

The necessary notebook grader support would be a way to specify the `--ExecutePreprocessor.kernel_name` when autograding.  There's possibly a lot more configuration that would need to be done to make a docker environment able to run the code, depending on how difficult the course is.  But it can be done via pass-through options in the setup phase.  I'll help a few courses here get set up to use this, and improve based on that experience.  It could also be modified to support e.g. singularity.  The general concept of these kernel wrappers is quite general and could use some development.  Does anyone know of similar things that already exist, besides those two links above?

What do you think?

**Comment by rkdarst** [comment]
This is a newer version of my isolation script.  It's more easily generalizeable to other isolation systems:
  https://github.com/AaltoScienceIT/envkernel

but the docs don't explain nbgrader specifically (and it's not just for docker/singularity), other types of adjusted environments can be set.  In general I need to update the docs more.

**Comment by jhamrick** [comment]
This looks really awesome! Though I guess there's probably some additional work that needs to be done if you need to mount other files that are not in the working directory? Still, as long as it works with simple assignments out of the box, that's really excellent. I haven't personally tested it yet but I'll try to play around with it soon.

It would be great to see how this goes with other courses, and if it seems to work well for them too then maybe we can figure out how to integrate it officially as part of nbgrader.

**Comment by rkdarst** [comment]
Yes, other files may need to be mounted inside, but envkernel can do that.  It can pass through any needed options.  Here is initial docs - actually yesterday I did my very first successful isolated autograding!  I used Singularity instead of Docker.

Create the isolated kernel.  This makes a new Jupyter kernel (`envkernel singularity` means singularity create mode) named `testcourse-0.5.9` out of the image `/l/simg/0.5.9.simg` with the Singularity options `-c` (contain, on default mounts) and `--bind` (bind a dir).  `--pwd` is handled inside the envkernel (and really, this should be made the default to not use an option... jupyter always assumes chdir to the notebook path).
```
envkernel singularity --sys-prefix --name=testcourse-0.5.9 /l/simg/0.5.9.simg -c --pwd --bind /m/jhnas/jupyter/course/testcourse/data/:/coursedata
```

Then to run autograding, which looks pretty normal:
```
nbgrader autograde --ExecutePreprocessor.kernel_name=testcourse-0.5.9 R1_Introduction
```

For reference this is what the Jupyter kernel looks like.  Most options are passed through without change, but may be re-processed by the `envkernel` again before running.  This could be made to work with non-IPython kernels too.  And it can accept arbitrary Singularity options.  The use is almost identical for Docker, but may need some testing first.
```
{
    "argv": [
        "/opt/conda-nbserver-0.5.9/bin/envkernel",
        "singularity",
        "run",
        "--connection-file",
        "{connection_file}",
        "/l/simg/0.5.9.simg",
        "-c",
        "--pwd",
        "--bind",
        "/m/jhnas/jupyter/course/testcourse/data/:/coursedata",
        "--",
        "python",
        "-m",
        "ipykernel_launcher",
        "-f",
        "{connection_file}"
    ],
    "display_name": "Singularity with /l/simg/0.5.9.simg",
    "language": "python"
}
```

**Comment by jhamrick** [comment]
FYI @nthiery you might be interested in this too!

**Comment by nthiery** [comment]
Oh yes! Thanks for the pointer. I'd be happy to sprint on this with you in Edinburgh!

**Comment by gertingold** [comment]
After application of PR NordicHPC/envkernel#1 to ``envkernel``, I succeeded in doing grading with a kernel running in a docker container. The required information can basically be found in the preceding discussion and the README at https://github.com/NordicHPC/envkernel. If there is interest in a coherent write-up, I can offer to work on it. Thanks a lot to @rkdarst for providing ``envkernel``.

**Comment by jhamrick** [comment]
@gertingold I think it would be great to include a page in the docs on this! I think it could fit in nicely under "advanced topics"---if you want to take a pass at this that would be awesome 😄

**Comment by rkdarst** [comment]
I just updated the envkernel readme a bit to include basic docker info (untested if it's correct), and revised nbgrader stuff a bit.  Anything from here can be copied to nbgrader documentation (even removed from envkernel if master copy belongs somewhere else).

I tried to use standard jupyter license, but I don't know if it actually is standard license.  Anyway whatever the nbgrader license is is fine.

**Comment by gertingold** [comment]
Thanks a lot @rkdarst for the update of the readme. I will try to prepare a PR for the ``nbgrader`` docs on that basis.

Since ``envkernel`` supports both ``docker`` and ``singularity``, I am wondering whether in the ``nbgrader`` docs we should discuss both options in detail or whether we should focus on one of them. Personally, I only have practical experience with the combination of ``docker`` and ``nbgrader`` so far, but we should of course have in mind the typical use case for ``nbgrader`` users. @jhamrick: Do you think that there is a preference for either ``docker`` or ``singularity`` in the community or is it best to discuss both in some detail?

**Comment by nthiery** [comment]
> Thanks a lot @rkdarst for the update of the readme. I will try to prepare a PR for the ``nbgrader`` docs on that basis.
> 
> Since ``envkernel`` supports both ``docker`` and ``singularity``, I am wondering whether in the ``nbgrader`` docs we should discuss both options in detail or whether we should focus on one of them. Personally, I only have practical experience with the combination of ``docker`` and ``nbgrader`` so far, but we should of course have in mind the typical use case for ``nbgrader`` users. @jhamrick: Do you think that there is a preference for either ``docker`` or ``singularity`` in the community or is it best to discuss both in some detail?    

If this does not lead to too much complication or confusion, I would
go for documenting both, to help users reuse existing local
infrastructure they may already have, be it docker or singularity.

If a choice needs to be done, I presume docker is more widespread.

Looking forward to test this later this week (on docker :-) ). Happy
to proofread / beta test documentation.

**Comment by rkdarst** [comment]
My idea was that it's fine to document only one.  A clever person
should be able to check the envkernel docs and adapt to whatever other
type of environment they may need.

But maybe some sort of minimal examples/discussion of both would be
good?

**Comment by nthiery** [comment]
> My idea was that it's fine to document only one.  A clever person
> should be able to check the envkernel docs and adapt to whatever other
> type of environment they may need.
> 
> But maybe some sort of minimal examples/discussion of both would be
> good?

Focusing on docker, and providing pointers / minimal examples for
Singularity in a few key spots can be a good enough way to support
both indeed.

**Comment by gertingold** [comment]
That sounds like a good approach. I will try to come up with a first proposal either tomorrow or during the weekend and then we can still iterate a bit.
