### ISSUE TITLE
Please consider adding a multi-choice selection option [Enhancement]

### ISSUE THREAD

**Issue by GadgetSteve** [jupyter/nbgrader#524]
When designing tests it is not uncommon to have some questions, or sections, that are multiple choice - this could also extent the usefulness of nbgrader to outside of the computer science field as many other disciplines could use it for preparing and grading tests.

**Comment by jhamrick** [comment]
I agree it would be very nice to have something like this, but I'm not sure it's possible to do in a language-agnostic way -- it could certainly be done in separate extensions for different kernels, though (e.g. using `ipywidgets` for the IPython kernel). But because it isn't language agnostic, I don't think this is something we can include in the nbgrader core, unfortunately.

Perhaps @dsblank has an extension that does this, or otherwise knows of one that might exist?
