### ISSUE TITLE
NBGrader installation file permissions

### ISSUE THREAD

**Issue by huwf** [jupyter/nbgrader#529]
Hi,

I'm trying to use nbgrader on `jupyterhub/systemuser`.  It installs and activates okay, but it seems to create some files as `root`, notably `.jupyter` and `.nbgrader.log`, which breaks all the `nbgrader xxxx` commands as it tries to write to `.jupyter/migrate` or `.nbgrader.log`.  File permissions:

    huwf@fb117aa6ded8:~$ ls -al   
	total 40   
	drwxr-xr-x  5 huwf  1007 4096 Jul 27 23:31 .  
	drwxr-xr-x 11 root  root  4096 Jul 27 23:30 .. 
	-rw-------  1 root  root   127 Jul 27 23:53 .bash_history  
	-rw-r--r--  1 huwf  1007  220 Aug 31  2015 .bash_logout   
	-rw-r--r--  1 huwf  1007 3771 Aug 31  2015 .bashrc
	drwxr-xr-x  3 huwf  1007 4096 Oct 21  2015 .config
	drwxr-xr-x  3 root  root  4096 Jul 27 23:30 .jupyter   
	drwx------  3 huwf huwf 4096 Jul 27 23:30 .local 
	-rw-r--r--  1 root  root  1036 Jul 27 23:30 .nbgrader.log  
	-rw-r--r--  1 huwf  1007  655 Jun 24 15:44 .profile

My guess is that I've missed something for the installation and activation, but I haven't noticed anything else in documentation.  Since I'm currently installing in the `Dockerfile` as

    RUN python3 -m pip install nbgrader==0.3.0
    RUN nbgrader extension install --symlink --debug

And activating in `systemuser.sh` doing

    nbgrader extension activate

it's running as root.  If I try using `USER` in the dockerfile, then it (unsurprisingly) gets a permission error when trying to build.

Any insights would be very gratefully received! :)

Thanks!

**Comment by huwf** [comment]
I had a bit more of a look for information about nbextensions, and I seem to have solved this (for now).  It may be the proper way of doing it, a workaround, or a hack.  Basically, I copied the contents of `~/.jupyter/` and then mounted to that in `jupyterhub_config.py`

    here = os.path.dirname(__file__)
    c.SystemUserSpawner.volumes = {'%s/.jupyter' % here: '/home/{username}/.jupyter'}

This seems to create the file with the correct user/group and I can run `nbgrader list` without it giving a permissions error.  I don't even have to run `nbgrader activate` because it's already loaded as part of the notebook config?

**Comment by jhamrick** [comment]
Glad you were able to find a solution to this. The one thing that might be a concern is that if people want to edit their own `.jupyter` directories, they can't (I think?) because it won't be the version in their home directory that is mounted but the version in the docker container, which would get reset each time the container restarts.

The way I dealt with this was to create a skeleton home directory with the relevant files:

https://github.com/compmodels/jupyterhub-deploy/blob/master/roles/restuser/tasks/skeldir.yml

And then whenever a user was created, use the skeleton home directory to create their home directory. That's also not the most elegant solution, though.
