### ISSUE TITLE
Student notebook dashboard features for non-shared filesystem

### ISSUE THREAD

**Issue by zpincus** [jupyter/nbgrader#569]
Currently the "notebook dashboard" features (assignment fetching, viewing, validating, etc.) rely on having a shared filesystem for all students.

A potentially useful enhancement would be to enable some of those features to work standalone -- especially the features for viewing and validating problem sets:
![](https://nbgrader.readthedocs.io/en/stable/_images/assignment_list_downloaded_expanded.png)

**Comment by willingc** [comment]
@zpincus Cool thoughts.

**Comment by jhamrick** [comment]
@zpincus said over email:

> How does the student dashboard currently know what assignments exist and where to fetch them? Is there a shared configuration file that gets updated when new assignments are released? If so, one possibility might be to make that config file location be a URL so that it could be fetched over the network. This, plus support for assignment locations as URLs-to-zipped-directories, could simplify distribution for the non-shared-filesystem case. (Turning in assignments is still tricky, though. Except for the obvious challenge of authentication, a simple HTTP POST system could be set up easily enough.)

Unfortunately there's not. The way it works with the shared filesystem is that there is a shared directory (the "exchange" directory) that released assignments get copied to. The Assignment List extension looks in that folder to see if there are any assignments that have been released and then out of the assignments that have been released, looks to see if those are in the students's home directory.

I don't think it's feasible to have something that will give exactly the same view as the Assignment List extension for students who are not on a shared filesystem (at least not how nbgrader is currently architected -- in the future, I hope to rework some of the assignment distribution stuff using something RESTful so that it can work whether you're running a shared server or not. That's going to be a really major change though.)

What I was thinking is something along the lines of adding a button the notebook view itself which runs `nbgrader validate` on the notebook, e.g. here:

![image](https://cloud.githubusercontent.com/assets/83444/18962887/6925d2f4-8627-11e6-91bc-32552085626a.png)

> If you think this would be a useful set of changes that wouldn't require rearchitecting everything, I'll add that to the github issue, and consider trying my hand at implementing it as a "learning nbgrader internals" exercise.

It would definitely be useful to have the "validate" extension though it might be a lot of work for a first PR, as it will require creating an entirely new extension. If you do want to take a pass at it though that would be really awesome!

**Comment by zpincus** [comment]
>  The way it works with the shared filesystem is that there is a shared directory (the "exchange" directory) that released assignments get copied to. The Assignment List extension looks in that folder to see if there are any assignments that have been released and then out of the assignments that have been released, looks to see if those are in the students's home directory.

Aha, that makes sense! So it's definitely more than a small project to change this behavior :)

Though step 1 might be just abstracting out the "find and fetch new assignments" functionality behind some simple API, with the default implementation being "look in the exchange directory on the filesystem". In the future, alternate implementations to provide RESTful or whatever behavior might be easier to add. I might play with this at some point just to see if I can learn the internals better.

> What I was thinking is something along the lines of adding a button the notebook view itself which runs nbgrader validate on the notebook.

Gotcha, that's definitely simpler and more straightforward.
