### ISSUE TITLE
Document how to update notebooks to v1 nbgrader metadata

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#627]
I saw the when I did nbgrader assign, it found v0 metadata. How do I update my notebooks to use the v1 metadata format?

**Comment by jhamrick** [comment]
There isn't a super easy way to do it at the moment, but it should be fine (it will just print out a warning and update them on-the-fly automatically). I haven't added support for manually updating the metadata yet because I haven't quite figured out how to do the schema validation in the javascript frontend.

Would it be better if there was just no warning printed out?

**Comment by ellisonbg** [comment]
Maybe an nbgrader command line subcommand?
