### ISSUE TITLE
New nbgrader record subcommand

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#65]
I have found that it caused problems to have the autograde step also record the grades in the db. I think there should be an `nbgrader record` subcommand that *only* records the grades that are in the notebook in the db. A side effect of this is that the autograde command should only do the autograding and save the autograde score in the notebook metadata itself. This creates a more modular and loosly coupled system.

**Comment by jhamrick** [comment]
I like this idea a lot, though it does add an extra step that instructors then have to remember to do.

Out of curiosity -- what were the problems that happened when the autograde step also recorded stuff into the database?

**Comment by ellisonbg** [comment]
As I went through the process of grading, I ended up re-doing lots of steps multiple times. Sometimes it was a problem with a notebook or notebooks. Sometimes my solutions had a bug. Other times, students handed in their notebooks late, so I had to rerun different steps. I found that it was really helpful to have very fine grained control over which parts I was rerunning at what times.

I should also mention that I didn't run the "record" step until abolutely everything (autograding + manual grading) was completely done for an assignment. Doing the record step last, as a sort of "commit"-like step allowed me to mess up the previous steps many times, redo them, etc. knowing that until I did "record" at the end, the grades weren't in the db. 

Before I split this out as a separate command I found myself battling against the state of the database relative to the state of the notebooks. There were probably other bugs I was running into, but the separation really helped.

**Comment by jhamrick** [comment]
Yeah, having fine grained control like that is going to be really important. I had that in the autograder I wrote for the class last year, where you could tell it to do a variety of things like the following:

* regrade a certain problem for all students
* regrade all problems for one student
* regrade a problem for a subset of students
* etc.

That functionality will definitely need to be added to nbgrader as well. 

This all brings up a related point which is: `nbgrader autograde`, `nbgrader record` and `nbgrader formgrade` need to know the hierarchy of notebooks on disk in relation to the assignment name, the problem name, and the student's name -- otherwise they won't be able to save/read the grades for a particular problem/student/etc.. I don't know what the best or most intuitive way to handle this is. One option is that we figure out a way to allow different instructors to organize submissions in whatever way they want, and they just have to configure nbgrader to tell it how that is. Or, we could say "you have to organize your notebooks like this or nbgrader won't know what to do".

**Comment by ellisonbg** [comment]
That is the *exact* question. I truly don't know the answer to it and I am curious to see how that aspect of file organization goes for you. I start teaching with all of this April 1st myself, so as the quarter goes on, I will be getting back to working on it more (grant writing now!).

It would be good to have some time to talk more about nbgrader when we have our next dev meeting at Berkeley (March 9-12), if you are around.

**Comment by jhamrick** [comment]
Currently my file organization is this:

```
<assignment name>/
    source/
    release/
    submitted/
        <student id 1>/
        <student id 2>/
        ...
    autograded/
        <student id 1>/
        <student id 2>/
        ....
```

where each folder then contains the files for the problem set (e.g. `Problem 1.ipynb`, `Problem 2.ipynb`, etc.). Then, `source` is the original/solutions, `release` is generated by `nbgrader assign`, `submitted` contains the original submissions from students, and `autograded` contains the autograded submissions. I have `submitted` and `autograded` be different because the autograder modifies the notebooks, so I like to start from the same original notebook every time.

I will definitely be around then and it's on my calendar, so let's be sure to set aside some time to talk about nbgrader stuff.

**Comment by ellisonbg** [comment]
My organization of files was almost identical to that, but I had the
source/release stuff in a separate tree. But I think that makes sense for a
jupyterhub deployment (in my class they used anaconda).

OK, I will make sure we put time for nbgrader on the agenda.

On Tue, Jan 20, 2015 at 5:34 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Currently my file organization is this:
>
> <assignment name>/
>     source/
>     release/
>     submitted/
>         <student id 1>/
>         <student id 2>/
>         ...
>     autograded/
>         <student id 1>/
>         <student id 2>/
>         ....
>
> where each folder then contains the files for the problem set (e.g. Problem
> 1.ipynb, Problem 2.ipynb, etc.). Then, source is the original/solutions,
> release is generated by nbgrader assign, submitted contains the original
> submissions from students, and autograded contains the autograded
> submissions. I have submitted and autograded be different because the
> autograder modifies the notebooks, so I like to start from the same
> original notebook every time.
>
> I will definitely be around then and it's on my calendar, so let's be sure
> to set aside some time to talk about nbgrader stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/65#issuecomment-70769480>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
I think probably once #144 is fixed we won't need to add this anymore. With the live notebook grading extension, we can add save hooks that automatically save stuff into the database, so there won't need to be an extra step of running `nbgrader record`.
