### ISSUE TITLE
List assignment extension reading invalid JSON

### ISSUE THREAD

**Issue by huwf** [jupyter/nbgrader#710]
A problem I came across just now was to do with the list assignment extension.  This was in 0.4.0rc1

For the extension, we have `assignments = json.loads(stdout.decode())`, which has the effect of including any other printed lines in `nbgrader_config.py`.  I had an old debug line `print("I'm in the config file"` in my file, which led to JSON being invalid.

A possibility is to search for a regex string for JSON, e.g., `json.loads(re.findall("\[[^\]]*\]", stdout)[0])`

Possibly a better solution is to include a warning in the error message, because of course a regex is fallible as well!

**Comment by jhamrick** [comment]
Ah, yes, this is not something I had anticipated. We can definitely try to do better reporting around this.

A better fix will happen if we can find a good way to fix #705, in which case we can actually just make a function call that will return the correct result rather than having to shell out and parse the stdout.

**Comment by jhamrick** [comment]
Just as an update, this is no longer a problem with `nbgrader list`, but it is still a problem with `nbgrader validate`.
