### ISSUE TITLE
setting nbgrader log-level by numeric value seems to have no effect.

### ISSUE THREAD

**Issue by Szepi** [jupyter/nbgrader#740]
I was trying to use:

```nbgrader zip_collect practice-final --force --log-level=XX --FileNameCollectorPlugin.named_regexp=".*_(?P<student_id>\w+)_assignsubmission_file_(?P<file_id>\w+)"```

with XX in 0,30,40, or 50. Only 30 seems to work, the others seem to turn off logging.
Specifying DEBUG or INFO worked.

**Comment by jhamrick** [comment]
This might be a larger Jupyter issue as nbgrader doesn't implement the logging machinery itself, but I'll look into it. Thanks!

**Comment by jhamrick** [comment]
I am having some trouble reproducing this, and am wondering if this might be expected behavior. The numbers correspond to levels as follows:

* 0 -- off
* 10 -- DEBUG
* 20 -- INFO
* 30 -- WARN
* 40 -- ERROR
* 50 -- CRITICAL

so 0, 40 and 50 shouldn't produce anything unless there are actually errors.

Can you run your command with 10 and 20 and let me know if the output is different from what you get if you use `DEBUG` and `WARN`?

**Comment by jhamrick** [comment]
@Szepi is this still a problem for you? If not, then I would like to close this issue.

**Comment by Szepi** [comment]
Hmm, I must have done something incorrectly as this seems to work now. Maybe I was in the wrong directory or something. Feel free to close this issue and sorry for the false alarm.

**Comment by jhamrick** [comment]
No problem, glad it's working now!
