### ISSUE TITLE
nbgrader autograde quits when one student doesn't submit

### ISSUE THREAD

**Issue by embanner** [jupyter/nbgrader#744]
When I run `$ nbgrader autograde assignment` and there is a student who has not submitted I get the error

```bash
[AutogradeApp | ERROR] No notebooks were matched in ...
```

and nbgrader quits. How can I skip over students who have not submitted and have nbgrader grade the submissions that students have submitted?

**Comment by embanner** [comment]
As a workaround I can write a script to grade student submission one-by-one via

```shell
$ for student in submitted/*
> do
> nbgrader autograde <assignment> --student=$(basename $student)
> done
```

but it would be nicer if I could just run

```shell
$ nbgrader autograde <assignment> --skip-missing
```

or something similar.

**Comment by jhamrick** [comment]
Hmm, I can only reproduce this if I have the following directory structure:

```
submitted/
    student1/
        ps1/
            notebook.ipynb
            ... other assignment files ...
    student2/
        ps1/
```

i.e., there are no files in the `submitted/student2/ps1` directory. I *think* this is expected behavior though, as there shouldn't be a problem set directory in the folder for the student if they haven't submitted the assignment. In other words, if you were to remove the `submitted/student2/ps1` directory, there wouldn't be an error. Can I ask what leads there to being a `submitted/student2/ps1` directory in the first place?

Regardless though, I think it's reasonable to handle this edge case and mark those notebooks as missing rather than throwing an error.

**Comment by embanner** [comment]
Sure what I do is create an empty shared `submission/<student>` folder for each student on Google Drive so they can submit their assignment. It remains empty until the student pastes in his or her solution.

**Comment by jhamrick** [comment]
Ah, I see, that's not a way I'd envisioned collecting assignments -- but I like it! That's totally reasonable then that you would want those folders to be there and to have nbgrader skip over them.
