### ISSUE TITLE
Update documentation about how to display the Create Assignment cell toolbars

### ISSUE THREAD

**Issue by BjornFJohansson** [jupyter/nbgrader#801]
Hi, I installed the newest version of nbgrader 0.5.1 with conda on python 3.6 and all the installation seem fine with no errors. I installed the toolbars using these commands, which finished without error messages.

     jupyter nbextension install --sys-prefix --py nbgrader --overwrite
     jupyter nbextension enable --sys-prefix --py nbgrader
     jupyter serverextension enable --sys-prefix --py nbgrader

However, I can not see the cell toolbars as depicted below. 

What should I do to see what is wrong? Or is there something I didn't get?

![screenshot from 2017-07-11 14-04-46](https://user-images.githubusercontent.com/9726401/28076542-fa468c96-6656-11e7-8141-6f2c1b11ec72.png)

**Comment by jhamrick** [comment]
You need to activate the cell toolbars, which you can do by going to View --> Cell Toolbar --> Create Assignment.

**Comment by jhamrick** [comment]
I am realizing this is different than what it says in [the documentation](http://nbgrader.readthedocs.io/en/stable/user_guide/creating_and_grading_assignments.html#developing-assignments-with-the-assignment-toolbar), so that's something that should be updated (there used to be a cell toolbar dropdown menu in the notebook, but it got removed and now lives in the View menu). Thanks for reporting this!

**Comment by BjornFJohansson** [comment]
Thanks, it worked!
