### ISSUE TITLE
Enforce uneditable test cells

### ISSUE THREAD

**Issue by nabriis** [jupyter/nbgrader#878]
Hi, 

I am wondering if there is a way to enforce a test cell to be uneditable by the student. Sometimes they accidentally change the test cells and the validation fails.

Or maybe a way to restore the test cells to their original state?

Edit: Seems it is the cell type that can be changed, not the actual content of the cell

**Comment by lgpage** [comment]
@nabriis with the newer version of Notebook a test cell does in a sense become locked so that it is not accidentally edited or deleted.

With regards to a student changing the cell type (e.g. from a code cell to markdown cell), I do not think it is possible to restrict this. It may however be possible to give better feedback from the validation for this scenario.

**Comment by jhamrick** [comment]
[Catching up on issues and PRs as I've been away for the last two months]

@lgpage is correct that even if the cell is marked as uneditable, it still appears possible to change the cell type (this is probably actually a bug in the notebook). However, I think even if the student changes the cell type, it should be changed back to the original cell type when `nbgrader autograde` is run. But this is definitely something that the validation could do a better job of reporting so at least students know why it's failing.

**Comment by jhamrick** [comment]
I have opened https://github.com/jupyter/notebook/issues/2992 and https://github.com/jupyter/notebook/pull/2993 on the notebook repo to fix the underlying issue of allowing cell types to change even if they are marked as uneditable. In the meantime, I am also working on a fix in nbgrader itself to report validation errors better.
