### ISSUE TITLE
formgrader page not found

### ISSUE THREAD

**Issue by rameshjesswani** [jupyter/nbgrader#882]
I have installed jupyter nbgrader by following steps from this link:

http://nbgrader.readthedocs.io/en/stable/user_guide/installation.html

After installation when I try to click on formgrader I get

error: 404 : Not Found You are requesting a page that does not exist! 

Can anyone help me, how can i access this page?

**Comment by lgpage** [comment]
@rameshjesswani can you provide output from the terminal?

**Comment by rameshjesswani** [comment]
@lgpage  thanks for your time

Here it shows that formgrader is enabled:

![nbextension_list](https://user-images.githubusercontent.com/25647309/29994959-1e90173e-8fdd-11e7-8dfa-dd28617be84e.png)

Now this is how my jupyter notebook looks like: 

![jupyter_notebook](https://user-images.githubusercontent.com/25647309/29994961-3b7de51a-8fdd-11e7-95ea-8df0a9d7d248.png)

When I click on formgrader tab:
![formgrader](https://user-images.githubusercontent.com/25647309/29994962-49a26d6e-8fdd-11e7-9e66-ccbb4fcab548.png)

**Comment by rameshjesswani** [comment]
Issue resolved, I was making some mistakes during installation. 

Thanks

**Comment by lgpage** [comment]
@rameshjesswani I am glad you were able to sort this out.

**Comment by aytekinar** [comment]
I have the same problem on my Arch Linux machine.

I have installed `nbgrader` with
```
pip install --user nbgrader nbconvert
```
Below is a list of my user packages:
```
pip list --user --format=columns
Package            Version
------------------ -------
alembic            0.9.6  
bleach             2.1.2  
entrypoints        0.2.3  
html5lib           1.0.1  
ipykernel          4.7.0  
ipywidgets         7.0.5  
jsonschema         2.6.0  
jupyter            1.0.0  
jupyter-client     5.1.0  
jupyter-console    5.2.0  
jupyter-core       4.4.0  
mistune            0.8.3  
nbconvert          5.3.1  
nbformat           4.4.0  
nbgrader           0.5.4  
notebook           5.2.2  
pandocfilters      1.4.2  
python-editor      1.0.3  
qtconsole          4.3.1  
terminado          0.8.1  
testpath           0.3.1  
webencodings       0.5.1  
widgetsnbextension 3.0.8  
```
My `.local` directory is also added to my `PATH`:
```
printenv PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/aytekin/.gem/ruby/2.4.0/bin:/opt/gurobi/bin:/home/aytekin/.local/bin
```
Finally I install
```
jupyter-nbextension install --user --py nbgrader
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/create_assignment -> create_assignment
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/create_assignment/main.js
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/create_assignment/create_assignment.css
- Validating: OK
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/formgrader -> formgrader
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/formgrader/main.js
- Validating: OK
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/validate_assignment -> validate_assignment
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/validate_assignment/main.js
- Validating: OK
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/assignment_list -> assignment_list
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/assignment_list/assignment_list.js
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/assignment_list/main.js
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/assignment_list/assignment_list.css
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable nbgrader --user --py
```
and enable `nbgrader` for my `jupyter` platform
```
jupyter-nbextension enable --user --py nbgrader
Enabling notebook extension create_assignment/main...
      - Validating: OK
Enabling tree extension formgrader/main...
      - Validating: OK
Enabling notebook extension validate_assignment/main...
      - Validating: OK
Enabling tree extension assignment_list/main...
      - Validating: OK
```
which can be verified by
```
jupyter-nbextension list --user
Known nbextensions:
  config dir: /home/aytekin/.jupyter/nbconfig
    notebook section
      create_assignment/main  enabled 
      - Validating: OK
      validate_assignment/main  enabled 
      - Validating: OK
    tree section
      formgrader/main  enabled 
      - Validating: OK
      assignment_list/main  enabled 
      - Validating: OK
```

When I issue `jupyter-notebook` and proceed to `Formgrader`, I see a 404 error.

Any idea?

**Comment by jhamrick** [comment]
Hi Arda, did you also enable the server extension (with `jupyter
serverextension enable`)? I am on my phone and can't give the exact command
right now but it is in the installation instructions in the docs.

If you have enabled that can you please paste the command line out put of
the jupyter server?

On Dec 14, 2017 11:17 AM, "Arda Aytekin" <notifications@github.com> wrote:

I have the same problem on my Arch Linux machine.

I have installed nbgrader with

pip install --user nbgrader nbconvert

Below is a list of my user packages:

pip list --user --format=columns
Package            Version
------------------ -------
alembic            0.9.6
bleach             2.1.2
entrypoints        0.2.3
html5lib           1.0.1
ipykernel          4.7.0
ipywidgets         7.0.5
jsonschema         2.6.0
jupyter            1.0.0
jupyter-client     5.1.0
jupyter-console    5.2.0
jupyter-core       4.4.0
mistune            0.8.3
nbconvert          5.3.1
nbformat           4.4.0
nbgrader           0.5.4
notebook           5.2.2
pandocfilters      1.4.2
python-editor      1.0.3
qtconsole          4.3.1
terminado          0.8.1
testpath           0.3.1
webencodings       0.5.1
widgetsnbextension 3.0.8

My .local directory is also added to my PATH:

printenv PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/aytekin/.gem/ruby/2.4.0/bin:/opt/gurobi/bin:/home/aytekin/.local/bin

Finally I install

jupyter-nbextension install --user --py nbgrader
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/create_assignment
-> create_assignment
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/create_assignment/main.js
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/create_assignment/create_assignment.css
- Validating: OK
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/formgrader
-> formgrader
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/formgrader/main.js
- Validating: OK
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/validate_assignment
-> validate_assignment
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/validate_assignment/main.js
- Validating: OK
Installing /home/aytekin/.local/lib/python3.6/site-packages/nbgrader/nbextensions/assignment_list
-> assignment_list
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/assignment_list/assignment_list.js
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/assignment_list/main.js
Up to date: /home/aytekin/.local/share/jupyter/nbextensions/assignment_list/assignment_list.css
- Validating: OK

    To initialize this nbextension in the browser every time the
notebook (or other app) loads:

          jupyter nbextension enable nbgrader --user --py

and enable nbgrader for my jupyter platform

jupyter-nbextension enable --user --py nbgrader
Enabling notebook extension create_assignment/main...
      - Validating: OK
Enabling tree extension formgrader/main...
      - Validating: OK
Enabling notebook extension validate_assignment/main...
      - Validating: OK
Enabling tree extension assignment_list/main...
      - Validating: OK

which can be verified by

jupyter-nbextension list --user
Known nbextensions:
  config dir: /home/aytekin/.jupyter/nbconfig
    notebook section
      create_assignment/main  enabled
      - Validating: OK
      validate_assignment/main  enabled
      - Validating: OK
    tree section
      formgrader/main  enabled
      - Validating: OK
      assignment_list/main  enabled
      - Validating: OK

When I issue jupyter-notebook and proceed to Formgrader, I see a 404 error.

Any idea?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyter/nbgrader/issues/882#issuecomment-351682700>,
or mute
the thread

**Comment by aytekinar** [comment]
I am very sorry @jhamrick.

You are right! In the installation instructions, you have the following:
```
jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --sys-prefix --py nbgrader
jupyter serverextension enable --sys-prefix --py nbgrader
```
I was lazy and sloppy enough to just read the `nbextension` part.

Now it is working. Thanks!

**Comment by mrios22** [comment]
I'm having trouble getting formgrader to work on my system to work. Everything else seems to work -- but formgrader doesn't seem to be importable. I'm not sure why. 

``` 
jupyter-xxxx@homeworkserver:~/.local/bin$ jupyter serverextension list
config dir: /home/jupyter-xxxx/.jupyter
    nbgrader.server_extensions.formgrader  enabled
    - Validating...
      nbgrader.server_extensions.formgrader  OK
    nbgrader.server_extensions.validate_assignment  enabled
    - Validating...
      nbgrader.server_extensions.validate_assignment  OK
    nbgrader.server_extensions.assignment_list  enabled
    - Validating...
      nbgrader.server_extensions.assignment_list  OK
    formgrader  enabled
    - Validating...
Error loading server extension formgrader
      X is formgrader importable?
config dir: /opt/tljh/user/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 0.35.4 OK
    nbgitpuller  enabled
    - Validating...
      nbgitpuller 0.6.1 OK
    nteract_on_jupyter  enabled
    - Validating...
      nteract_on_jupyter 2.0.7 OK
    nbresuse  enabled
    - Validating...
      nbresuse  OK
```

**Comment by jhamrick** [comment]
Hi @mrios22 , can you please open a new issue for this?
