### ISSUE TITLE
Formgrader manual grading version does not load attached files

### ISSUE THREAD

**Issue by bogaaak** [jupyter/nbgrader#950]
### Operating system
MacOS X 10.13.2

### `nbgrader --version`
Python version 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
nbgrader version 0.5.4

### `jupyter notebook --version` 
5.0.0

### Expected behavior
Student's load attached figures and discuss them inside "Manually graded answer"-markdown-cells. 
They use, for example,  `![figure.png](attachment:figure.png)`
<img width="1030" alt="figure_within_manually_graded_answer_cell" src="https://user-images.githubusercontent.com/3419333/39475526-60c609e8-4d50-11e8-9c57-a4170a6b3578.png">
Opening the notebook from the `autograded/` directory displays the figure as wanted.

### Actual behavior

Within the formgrader-html version, however, the figure is not loaded.
<img width="951" alt="formgrader_not_loading" src="https://user-images.githubusercontent.com/3419333/39475472-362120a6-4d50-11e8-8f81-86bfe5cc4c91.png">

Is there a way to make the formgrader version access the figure and load it? 
At the moment, I have to open notebook for each student and have to switch back and forth betweenn formgrader- and notebook-versions.

### Steps to reproduce the behavior
Load a local file (figure) in a manually graded-answer cell and open the "Manual grading"-version of the autograded notebook.

Thank you very much for any help. Nbgrader is so useful!

**Comment by jhamrick** [comment]
Ah, this indeed seems to be a bug---the formgrader currently doesn't support notebook attachments (but it should). I don't think there's anything you can do for this assignment to make them display, unfortunately, but what I would suggest for future assignments (until the bug is fixed) is to have students save the image to a file and then load the file as an image (rather than loading the attachment). Loading an actual file from disk should work:

![image](https://user-images.githubusercontent.com/83444/39602335-c945c648-4f1c-11e8-9209-820f26975804.png)

**Comment by jhamrick** [comment]
Related: https://github.com/jupyter/nbconvert/issues/699

**Comment by Alexanderallenbrown** [comment]
@jhamrick I'd like to take a crack at fixing this, because my students often use attached images as part of their solutions... but I think my "fix" might not be structurally appropriate, and it had almost nothing to do with nbgrader. My approach was, after looking at the nbconvert issue you referenced above and reading over the proposed workarounds, to modify [nbconvert/exporters/html.py](https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/html.py). My changes to this file, basically copied directly from @platise workaround in the nbconvert issue, were as follows:

```python
   def from_notebook_node(self, nb, resources=None, **kw):
        langinfo = nb.metadata.get('language_info', {})
        lexer = langinfo.get('pygments_lexer', langinfo.get('name', None))
        self.register_filter('highlight_code',
                             Highlight2HTML(pygments_lexer=lexer, parent=self))
        #begin additions
        body,res = super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
        # Create a list saving all image attachments to their base64 representations
        images = []
        for cell in nb['cells']:
            if 'attachments' in cell:
                attachments = cell['attachments']
                for filename, attachment in attachments.items():
                    for mime, base64 in attachment.items():
                        images.append( [f'attachment:{filename}', f'data:{mime};base64,{base64}'] )

        # Fix up the HTML and write it to disk
        for itmes in images:
            src = itmes[0]
            base64 = itmes[1]
            body = body.replace(f'src="{src}"', f'src="{base64}"', 1)
        #end additions
        return body,res#super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
``` 

I guess one question is: does it make sense to close this issue since this can be solved by fixing a bug in nbconvert itself, or does it make sense for us to modify the formgrader app and/or the nbgrader feedback command to wrap these changes in independent of the nbconvert system?

**Comment by jhamrick** [comment]
Yeah, if this is something that is fixed in nbgrader via the workarounds listed in the nbconvert issue, then I think it makes sense to close this issue and try to get it fixed upstream in nbconvert.
