### ISSUE TITLE
Unclarity on directory structure / configuration

### ISSUE THREAD

**Issue by murhum1** [jupyter/nbgrader#980]
I'm currently trying to set up a jupyter notebook environment for a course of >600 students using kubernetes + jupyterhub + nbgrader. Everything jupyterhub-related seems to be working fine so far, but I'm having issues understanding the nbgrader configuration regarding courses and assignments.

My environment currently consists of 3 kubernetes nodes: one for kubernetes related administrative things, one for the jupyterhub container, and one for notebook servers. I'm using [kube-spawner](https://github.com/jupyterhub/kubespawner) to spawn the notebook server containers.

Inside the container, I have 3 directories: `/course`, `/user`, and `/exchange`, all of which are empty to begin with. My `nbgrader_config.py` is as follows:
```
c = get_config()

c.Exchange.course_id = "example_course"
c.Exchange.root = "/exchange"

c.CourseDirectory.root = "/course"
```
And in `jupyterhub_config.py` I've defined `c.KubeSpawner.singleuser_working_dir = '/user'`.

Now I've no idea how I'd actually start creating a course. I've tried running `nbgrader quickstart my_course` in all of the 3 directories, but in all cases, in the jupyterhub "Assignments" tab it says "No courses available", and when I try to create an assignment in the "Formgrader" tab, I get an sql error `unable to open database file`. And in the UI I can't see the quickstart-created course anywhere, nor any assignments.

All in all I'm just really confused about how the configuration works, and the documentation is just a mess regarding this. Any ideas / pointers on what I should try?

For what it's worth,

### Operating system
Ubuntu 16.04

### `nbgrader --version`
0.5.4

### `jupyterhub --version` (if used with JupyterHub)
0.9.0

### `jupyter notebook --version` 
5.4.1

**Comment by consideRatio** [comment]
I [made a mindmap](https://drive.google.com/file/d/1W5bDmy6CoKITxMeiuv6HA5phR_NqPVif/view?usp=sharing) trying to figure out the details, I hope it is of use to you. In the mindmap you might be able to see the exchange folders as well as the `nbgrader` actions students and instructors can do, and what kinds of file system permissions are required for the actions.

I never made my jupyterhub (deployed using https://z2jh.jupyter.org) support nbgrader since it required me to setup a shared filesystem for the exchange directories, something I could not find time to do.

**Comment by jhamrick** [comment]
Glad you were able to figure this out! I'll note that you should be able to create `nbgrader_config.py` file in `/home/jovyan/.jupyter` rather than `jupyter_notebook_config.py`, but if this works then that's great. See also the note about the config file at the bottom of: https://nbgrader.readthedocs.io/en/stable/configuration/jupyterhub_config.html

**Comment by vishwesh5** [comment]
Hi @murhum1 I am also trying to use Zero to Jupyterhub installation (jupyterhub+kubernetes). So far what I have figured out is that I need to have a NFS installed. Let's say I manage to do that somehow, how can I use nbgrader along with it? Can you please give a few pointers regarding how you were able to have that up and running?
Thanks in advance

**Comment by rkdarst** [comment]
@vishwesh5, you can check out [this comment](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/174#issuecomment-410235452) to see our current state of things.  I hope to make better documentation soon.
